language: node_js
node_js:
  - lts/*

branches:
  only:
    - master

before_script:
  - npm install -g firebase-tools
  - npm install -g @angular/cli

script:
  - npm run build:prod

after_success:
  - test $TRAVIS_BRANCH = "master" && firebase deploy --token $FIREBASE_TOKEN

notifications:
  email:
    on_failure: change
    on_success: change
