language: node_js
node_js:
  - 'node'

branches:
  only:
    - master

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.10.1
  - export PATH=$HOME/.yarn/bin:$PATH

cache:
  yarn: true

before_script:
  - yarn global add firebase-tools
  - yarn global add @angular/cli

script:
  - yarn build:prod

after_success:
  - test $TRAVIS_BRANCH = "master" && firebase deploy --token $FIREBASE_TOKEN

notifications:
  email:
    on_failure: change
    on_success: change
