language: node_js
node_js:
  - lts/*

branches:
  only:
    - master

cache:
  yarn: true

before_script:
  - yarn global add firebase-tools
  - yarn global add @angular/cli

script:
  - yarn build:prod

after_success:
  - test $TRAVIS_BRANCH = "master" && firebase deploy --token $FIREBASE_TOKEN

notifications:
  email:
    on_failure: change
    on_success: change
